env:
  - GO111MODULE=on
builds:
  - id: akash-linux-amd64
    binary: akash-e2e-production
    main: ./cmd/e2e
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "{{ .Env.BUILD_FLAGS }}"
      - -trimpath
      - -mod=readonly
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -extldflags "--static"

archives:
  - format: binary

nfpms:
  - vendor: "Overclock Labs Inc."
    homepage: "https://ovrclk.com"
    maintainer: "Akash Network <hello@akash.network>"
    formats:
      - deb
    license: Apache 2.0

release:
  github:
    owner: ovrclk
    name: e2e-production
  prerelease: auto
  draft: false
