---
version: "2.0"

services:
  web:
    image: gambitcajun/sovryn-frontend:latest
    env:
      - TORPUB=
      - TORKEY=
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1024Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
       anyOf:
        - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 5000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
