name: release

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: install goreleaser
        run: |-
          wget $(curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -s https://api.github.com/repos/goreleaser/goreleaser/releases/latest | jq -r ".assets[] | select(.name | test(\"goreleaser_amd64.deb\")) | .browser_download_url") -O goreleaser.deb
          sudo dpkg -i goreleaser.deb
          rm goreleaser.deb
      - name: branch name
        id: branch_name
        run: |
          echo ::set-output name=GORELEASER_TAG::${GITHUB_REF#refs/tags/}
      - if: (github.ref == 'refs/heads/master')
        name: release dry-run GORELEASER_SKIP_VALIDATE=true
        run: make release-dry-run GORELEASER_SKIP_VALIDATE=true
      - if: startsWith(github.ref,'refs/tags/v')
        name: release dry-run
        run: make release-dry-run
      - if: startsWith(github.ref,'refs/tags/v')
        name: release publish
        run: |-
          sudo rm -rf dist
          make release
